/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.BankInformation;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.math.BigDecimal;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-12-01T14:58:07.832Z")

@Api(value = "banks", description = "the banks API")
@RequestMapping(value = "")
public interface BanksApi {

    @ApiOperation(value = "Get all banks list", nickname = "getAllBanksUsingGET", notes = "", response = BankInformation.class, responseContainer = "List", tags={ "banks-information-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BankInformation.class, responseContainer = "List") })
    @RequestMapping(value = "/banks/info",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<BankInformation>> getAllBanksUsingGET();


    @ApiOperation(value = "Get commission percentage by bank code", nickname = "getBankCommissionUsingGET", notes = "", response = BigDecimal.class, tags={ "banks-information-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BigDecimal.class) })
    @RequestMapping(value = "/banks/commission/{bankCode}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<BigDecimal> getBankCommissionUsingGET(@ApiParam(value = "bankCode",required=true) @PathVariable("bankCode") String bankCode);


    @ApiOperation(value = "Get currency by bank code", nickname = "getBankCurrencyUsingGET", notes = "", response = String.class, tags={ "banks-information-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = String.class) })
    @RequestMapping(value = "/banks/currency/{bankCode}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> getBankCurrencyUsingGET(@ApiParam(value = "bankCode",required=true) @PathVariable("bankCode") String bankCode);


    @ApiOperation(value = "Get information by bank code", nickname = "getBankInfoUsingGET", notes = "", response = String.class, tags={ "banks-information-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = String.class) })
    @RequestMapping(value = "/banks/info/{bankCode}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> getBankInfoUsingGET(@ApiParam(value = "bankCode",required=true) @PathVariable("bankCode") String bankCode);

}
